{{- if .Values.server.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "gocd.fullname" . }}-server
  labels:
    app: {{ template "gocd.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    component: server
  annotations:
    {{- range $key, $value := .Values.server.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
    - hosts:
      - gocd.shafayouxi.org
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for gocd.shafayouxi.io
      secretName: gocd-tls
  rules:
    - host: gocd.shafayouxi.org
      http:
        paths:
        - path: /
          backend:
            # This assumes http-svc exists and routes to healthy endpoints
            serviceName: gocd-server
            servicePort: 8153
